excerpt_separator: ""
rouge: true
markdown: kramdown
title: Quen-Quen Potter
tagline: Tales of a Web Developer
description: Web Development and Design
paginate: 3
author:
  quenquen:
    name: quenquen
    url: http://quenquen.github.io
    description: Web development from the view of a front-end Web Developer, focused on all things HTML, CSS and Javascript.
